---
title: "Project 1"
author: "Leilynaz Malekafzali (33305137)"
date: '2018-03-10'
output: html_document
---

```{r}
library("tidyverse")
library("phyloseq")
```


```{r}
setwd("/Users/Leilynaz/Documents/MICB425_portfolio/")
load("/Users/Leilynaz/Documents/MICB425_materials/Module_03/Project1/data/mothur_phyloseq.RData")
```

Samples were rarefied/normalized to 100,000 sequences per sample to facilitate comparisons between samples. A random seed was set to ensure reproducibility.
```{r}
set.seed(4832)
m.norm = rarefy_even_depth(mothur, sample.size=100000)
```

Rarefied counts were converted to relative abundance percentages.
```{r}
m.perc = transform_sample_counts(m.norm, function(x) 100 * x/sum(x))
```

### How does microbial community structure change with depth and oxygen concentration?
#### Alpha-diversity
```{r}
m.alpha = estimate_richness(m.norm, measures = c("Chao1", "Shannon"))

m.meta.alpha = full_join(rownames_to_column(m.alpha), rownames_to_column(data.frame(m.perc@sam_data)), by = "rowname")

m.meta.alpha
```

```{r}
m.meta.alpha %>% 
  
ggplot() +
  geom_point(aes(x=Depth_m, y=Shannon)) +
   geom_smooth(method='auto', aes(x=as.numeric(Depth_m), y=Shannon)) +
  labs(title="Example 1: Alpha-diversity across depth", y="Shannon's diversity index", x="Depth (m)")
```

```{r}
m.meta.alpha %>% 

ggplot() +
  geom_point(aes(x=O2_uM, y=Shannon)) +
  labs(title="Example 2: Alpha-diversity across oxygen", y="Shannon's diversity index", x="Oxygen (uM)")
```

```{r}
m.meta.alpha %>% 
  mutate(O2_group = ifelse(O2_uM == 0, "anoxic", "oxic")) %>% 

# Use this in a plot
ggplot() +
  geom_boxplot(aes(x=O2_group, y=Shannon)) +
  labs(title="Example 3: Alpha-diversity by oxic/anoxic", y="Shannon's diversity index", x="Oxygen")
```
